title: 결국 뭐라도 한다
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://hanshangom.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: SangHun Han # add your name
author-img: david-freeman.jpg # add your photo
about-author: 어떻게든 무언가 된다 # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hanshangom # add your Github handle
social-linkedin: https://www.linkedin.com/in/%EC%83%81%ED%9B%88-%ED%95%9C-760722170/ # add your Linkedin handle
social-email: zxcvb0294@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
